---
title: "BEE 4750 Homework 5: Mixed Integer and Stochastic Programming"
format:
    html:        
        warning: true
        error: true
    ipynb:
        warning: true
        error: true
        code-annotation: below
engine: julia
format-links: []
---

::: {.content-visible when-format="ipynb"}
**Name**:

**ID**:
:::

::: {.callout-important icon=false}
### Due Date

Thursday, 12/05/24, 9:00pm 
:::

::: {.content-visible when-format="html"}

:::{.callout-caution}

If you are enrolled in the course, make sure that you use the GitHub Classroom link provided in Ed Discussion, or you may not be able to get help if you run into problems.

Otherwise, you can [find the Github repository here]({{< var github_org.repo >}}/hw05).

:::

:::

## Overview

::: {.cell .markdown}

### Instructions

- In Problem 1, you will use mixed integer programming to solve a waste load allocation problem.

:::

::: {.cell .markdown}

### Load Environment

The following code loads the environment and makes sure all needed packages are installed. This should be at the start of most Julia scripts.

:::

```{julia}
#| output: false
import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```

```{julia}
using JuMP
using HiGHS
using DataFrames
using GraphRecipes
using Plots
using Measures
using MarkdownTables
```


## Problems (Total: 30 Points)

### Problem 1 (30 points)

Three cities are developing a coordinated municipal solid waste (MSW) disposal plan.  Three disposal alternatives are being considered: a landfill (LF), a materials recycling facility (MRF), and a waste-to-energy facility (WTE). The capacities of these facilities and the fees for operation and disposal are provided below.

- **LF**: Capacity 200 Mg, fixed cost \$2000/day, tipping cost \$50/Mg;
- **MRF**: Capacity 350 Mg, fixed cost \$1500/day, tipping cost \$7/Mg, recycling cost \$40/Mg recycled;
- **WTE**: Capacity 210 Mg, fixed cost \$2500/day, tipping cost \$60/Mg;

The MRF recycling rate is 40%, and the ash fraction of non-recycled waste is 16% and of recycled waste is 14%. Transportation costs are \$1.5/Mg-km, and the relative distances between the cities and facilities are provided in the table below. 

| **City/Facility**  |  **Landfill (km)** | **MRF (km)**  | **WTE (km)** |
|:-------------:|:------------:|:-------------:|:-------------:|
| 1  	  | 5  | 30 | 15 |
| 2 	  | 15 | 25 | 10 |
| 3       | 13 | 45 | 20 |
| LF	  | - | 32  | 18 |
| MRF	  | 32 | - | 15 |
| WTE	  |  18 | 15 | -  |

The fixed costs associated with the disposal options are incurred only if the particular disposal option is implemented.  The three cities produce 100, 90, and 120 Mg/day of solid waste, respectively, with the composition provided in the table below. 

**Reminder**: Use `round(x; digits=n)` to report values to the appropriate precision!


**In this problem**:

* Formulate the waste load allocation problem and implement it in `JuMP`.
* Draw a diagram showing the flows of waste between the cities and the facilities.  Which facilities (if any) will not be used? Does this solution make sense?


::: {.cell .markdown}
## References

List any external references consulted, including classmates.
:::